services:
  - type: worker
    name: nft-sales-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RESERVOIR_API_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
      - key: CHECK_INTERVAL
        value: 120
